# Dockerfile SIMPLES -- só empacota um .jar que JA EXISTE, sem Maven dentro do container
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# copia o .jar pronto (que já foi buildado ANTES, fora do Docker)
COPY target/funcionario-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
